extraVolumeMounts:
    - name: pods
      mountPath: /var/log/pods
      readOnly: true

extraVolumes:
    - name: pods
      hostPath:
        path: "/var/log/pods"
        type: Directory

elasticsearch:
  auth:
    enabled: false
    user: "yourUser"
    password: "yourPass"
  bufferChunkLimit: "2M"
  bufferQueueLimit: 8
  host: "elasticsearch-master.logging.svc.cluster.local"
  logstashPrefix: "logstash"
  port: 9200
  path: ""
  scheme: "http"
  sslVerify: true
  sslVersion: "TLSv1_2"
  outputType: "elasticsearch"
  typeName: "_doc"
  logLevel: "info"